{
  "required": [
    "guest_OS"
  ],
  "type": "object",
  "properties": {
    "cdroms": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.cdrom.create_spec"
      },
      "type": "array",
      "description": "List of CD-ROMs.\nIf unset, no CD-ROM devices will be created."
    },
    "placement": {
      "description": "Virtual machine placement information.\nIf unset, the system will attempt choose suitable resources on which to place the virtual machine.",
      "$ref": "#/definitions/com.vmware.vcenter.VM.placement_spec"
    },
    "name": {
      "type": "string",
      "description": "Virtual machine name.\nIf unset, a default name will be generated by the server."
    },
    "floppies": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.floppy.create_spec"
      },
      "type": "array",
      "description": "List of floppy drives.\nIf unset, no floppy drives will be created."
    },
    "boot": {
      "description": "Boot configuration.\nIf unset, guest-specific default values will be used.",
      "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.boot.create_spec"
    },
    "disks": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.disk.create_spec"
      },
      "type": "array",
      "description": "List of disks.\nIf unset, a single blank virtual disk of a guest-specific size will be created on the same storage as the virtual machine configuration, and will use a guest-specific host bus adapter type. If the guest-specific size is 0, no virtual disk will be created."
    },
    "boot_devices": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.boot.device.entry_create_spec"
      },
      "type": "array",
      "description": "Boot device configuration.\nIf unset, a server-specific boot sequence will be used."
    },
    "hardware_version": {
      "description": "Virtual hardware version.\nIf unset, defaults to the most recent version supported by the server.",
      "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.version"
    },
    "guest_OS": {
      "description": "Guest OS.",
      "$ref": "#/definitions/com.vmware.vcenter.vm.guest_OS"
    },
    "nics": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.ethernet.create_spec"
      },
      "type": "array",
      "description": "List of Ethernet adapters.\nIf unset, no Ethernet adapters will be created."
    },
    "parallel_ports": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.parallel.create_spec"
      },
      "type": "array",
      "description": "List of parallel ports.\nIf unset, no parallel ports will be created."
    },
    "memory": {
      "description": "Memory configuration.\nIf unset, guest-specific default values will be used.",
      "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.memory.update_spec"
    },
    "scsi_adapters": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.adapter.scsi.create_spec"
      },
      "type": "array",
      "description": "List of SCSI adapters.\nIf unset, any adapters necessary to connect the virtual machine's storage devices will be created; this includes any devices that explicitly specify a SCSI host bus adapter, as well as any devices that do not specify a host bus adapter if the guest's preferred adapter type is SCSI. The type of the SCSI adapter will be a guest-specific default type."
    },
    "sata_adapters": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.adapter.sata.create_spec"
      },
      "type": "array",
      "description": "List of SATA adapters.\nIf unset, any adapters necessary to connect the virtual machine's storage devices will be created; this includes any devices that explicitly specify a SATA host bus adapter, as well as any devices that do not specify a host bus adapter if the guest's preferred adapter type is SATA."
    },
    "cpu": {
      "description": "CPU configuration.\nIf unset, guest-specific default values will be used.",
      "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.cpu.update_spec"
    },
    "serial_ports": {
      "items": {
        "$ref": "#/definitions/com.vmware.vcenter.vm.hardware.serial.create_spec"
      },
      "type": "array",
      "description": "List of serial ports.\nIf unset, no serial ports will be created."
    }
  }
}
